# Generated by Django 6.0.2 on 2026-02-23 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_shop_alter_profile_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='company',
        ),
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.ForeignKey(default=59, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='api.location'),
        ),
    ]
