# Generated by Django 6.0.2 on 2026-02-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_company_location_remove_shop_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
    ]
