# Generated by Django 6.0.2 on 2026-02-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_profile_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='role_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='role_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='role_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='user_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='user_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='user_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='user_view',
            field=models.BooleanField(default=False),
        ),
    ]
