# Generated by Django 6.0.2 on 2026-02-24 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_role_company_role_location_role_shop_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='location',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='shop',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.shop'),
            preserve_default=False,
        ),
    ]
